spring.application.name=finance-track
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update

#chave secreta de assinatura
jwt.secret=8f4c9a7d1e2b3c4d5f6a7b8c9d0e1f2a3b4c5d6e7f8g9h0


